version: '3.7'
services:

  shopiloc:
    image: registry.gitlab.com/ecom_experts.io/shopiloc
    container_name: shopiloc
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    expose:
      - 27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
